//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsApp
{
    public partial class CustomerDetails
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// LoadingPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel LoadingPanel;

        /// <summary>
        /// NotFoundPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel NotFoundPanel;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// RetryButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button RetryButton;

        /// <summary>
        /// CustomerPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel CustomerPanel;

        /// <summary>
        /// NameLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label NameLabel;

        /// <summary>
        /// EmailLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label EmailLabel;
    }
}
