//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsApp
{
    public partial class CustomerCreate
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// NameTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NameTextBox;

        /// <summary>
        /// EmailTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;

        /// <summary>
        /// SaveButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SaveButton;
    }
}
