//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsApp
{
    public partial class Customers
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// RefreshButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button RefreshButton;

        /// <summary>
        /// LoadingPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel LoadingPanel;

        /// <summary>
        /// EmptyPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel EmptyPanel;

        /// <summary>
        /// ErrorPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;

        /// <summary>
        /// CustomersGrid control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView CustomersGrid;
    }
}
